spring: 
    progiles: 
        active: 
        -dev
---   
server: 
    port: 7001
    
spring: 
    progiles: dev   #开发环境
    appliction: 
        name: microservicecloud-config-eureka-client
eureka: 
    instance: 
        hostname: eureka7001.com
    client: 
        register-with-eureka: false   #当前eureka-server自己不注册进服务列表中
        fetch-registry: false   #不通过eureka获取注册信息
        service-url: 
            defaultZone: http://eureka700.com:7001/eureka
---   
server: 
    port: 7001
    
spring: 
    progiles: test   #开发环境
    appliction: 
        name: microservicecloud-config-eyreka-client
eureka: 
    instance: 
        hostname: eureka7001.com
    client: 
        register-with-eureka: false   #当前eureka-server自己不注册进服务列表中
        fetch-registry: false   #不通过eureka获取注册信息
        service-url: 
            defaultZone: http://eureka700.com:7001/eureka