spring: 
    progiles: 
        active: 
        -dev
---   
server: 
    port: 8001
    
spring: 
    progiles: dev   #开发环境
    appliction: 
        name: microservicecloud-config-dept-client
    datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: root
    dbcp2:
      min-idle: 5
      max-idle: 5
      initial-size: 5
      max-wait-millis: 200
      
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.hu.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
eureka: 
    client: 
        service-url: 
            defaultZone: http://eureka700.com:7001/eureka

info: 
  app.name: hu-microservicecloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---   
server: 
    port: 8001
    
spring: 
    progiles: test   #测试环境
    appliction: 
        name: microservicecloud-config-dept-client
    datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: root
    dbcp2:
      min-idle: 5
      max-idle: 5
      initial-size: 5
      max-wait-millis: 200
      
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.hu.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
eureka: 
    client: 
        service-url: 
            defaultZone: http://eureka700.com:7001/eureka

info: 
  app.name: hu-microservicecloud
  company.name: www.baidu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---   