spring: 
    progiles: 
        active: 
        -dev
---   
server: 
    port: 8201
    
spring: 
    progiles: dev   #开发环境
    appliction: 
        name: microservicecloud-config-client
eureka: 
    client: 
        service-url: 
            defaultZone: http://eureka-dev.com:7001/eureka
---   
server: 
    port: 8202
    
spring: 
    progiles: test   #开发环境
    appliction: 
        name: microservicecloud-config-client
eureka: 
    client: 
        service-url: 
            defaultZone: http://eureka-test.com:7001/eureka